

LIB = libmatrix.a
FILES   =   alloc demo jacobi norm qr system choleski inverse jordan operator quatern unary construc io lu points rotation vector creat is manip ql svdcmp 	
include ../makefile.inc

alloc.o: alloc.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
choleski.o: choleski.cpp matrix.h matrix.hh matrix.icc vector.hh \
  vector.icc points.hh quatern.hh
construc.o: construc.cpp matrix.h matrix.hh matrix.icc vector.hh \
  vector.icc points.hh quatern.hh
creat.o: creat.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
demo.o: demo.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
inverse.o: inverse.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
io.o: io.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc points.hh \
  quatern.hh
is.o: is.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc points.hh \
  quatern.hh
jacobi.o: jacobi.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
jordan.o: jordan.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
lu.o: lu.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc points.hh \
  quatern.hh
manip.o: manip.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
norm.o: norm.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
operator.o: operator.cpp matrix.h matrix.hh matrix.icc vector.hh \
  vector.icc points.hh quatern.hh
points.o: points.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
ql.o: ql.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc points.hh \
  quatern.hh
qr.o: qr.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc points.hh \
  quatern.hh
quatern.o: quatern.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
rotation.o: rotation.cpp matrix.h matrix.hh matrix.icc vector.hh \
  vector.icc points.hh quatern.hh
svdcmp.o: svdcmp.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
system.o: system.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
unary.o: unary.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
vector.o: vector.cpp matrix.h matrix.hh matrix.icc vector.hh vector.icc \
  points.hh quatern.hh
