# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ivfgeo', [dirname(__file__)])
        except ImportError:
            import _ivfgeo
            return _ivfgeo
        if fp is not None:
            try:
                _mod = imp.load_module('_ivfgeo', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ivfgeo = swig_import_helper()
    del swig_import_helper
else:
    import _ivfgeo
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


TFIDF_NO = _ivfgeo.TFIDF_NO
TFIDF_OXFORD = _ivfgeo.TFIDF_OXFORD
TFIDF_NISTER = _ivfgeo.TFIDF_NISTER
NB_BITS_VAL_ID = _ivfgeo.NB_BITS_VAL_ID
NB_BITS_VAL_SCALE = _ivfgeo.NB_BITS_VAL_SCALE
NB_BITS_VAL_ANGLE = _ivfgeo.NB_BITS_VAL_ANGLE
NB_BITS_VAL_BINSIGN = _ivfgeo.NB_BITS_VAL_BINSIGN
LOG_SCALE_QUANTIZATION_STEP = _ivfgeo.LOG_SCALE_QUANTIZATION_STEP
AS_MAX_0 = _ivfgeo.AS_MAX_0
AS_MAX_PREMULTIPLY = _ivfgeo.AS_MAX_PREMULTIPLY
AS_MAX_PREMULTIPLY_1 = _ivfgeo.AS_MAX_PREMULTIPLY_1
AS_MAX_PREMULTIPLY_3 = _ivfgeo.AS_MAX_PREMULTIPLY_3
AS_MAX_PREMULTIPLY_4 = _ivfgeo.AS_MAX_PREMULTIPLY_4
norm_none = _ivfgeo.norm_none
norm_type_1 = _ivfgeo.norm_type_1
norm_type_2 = _ivfgeo.norm_type_2
norm_type_1_sqrt = _ivfgeo.norm_type_1_sqrt
class ivfgeo_elem_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ivfgeo_elem_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ivfgeo_elem_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["id"] = _ivfgeo.ivfgeo_elem_t_id_set
    __swig_getmethods__["id"] = _ivfgeo.ivfgeo_elem_t_id_get
    if _newclass:id = _swig_property(_ivfgeo.ivfgeo_elem_t_id_get, _ivfgeo.ivfgeo_elem_t_id_set)
    __swig_setmethods__["scale"] = _ivfgeo.ivfgeo_elem_t_scale_set
    __swig_getmethods__["scale"] = _ivfgeo.ivfgeo_elem_t_scale_get
    if _newclass:scale = _swig_property(_ivfgeo.ivfgeo_elem_t_scale_get, _ivfgeo.ivfgeo_elem_t_scale_set)
    __swig_setmethods__["angle"] = _ivfgeo.ivfgeo_elem_t_angle_set
    __swig_getmethods__["angle"] = _ivfgeo.ivfgeo_elem_t_angle_get
    if _newclass:angle = _swig_property(_ivfgeo.ivfgeo_elem_t_angle_get, _ivfgeo.ivfgeo_elem_t_angle_set)
    __swig_setmethods__["binsign"] = _ivfgeo.ivfgeo_elem_t_binsign_set
    __swig_getmethods__["binsign"] = _ivfgeo.ivfgeo_elem_t_binsign_get
    if _newclass:binsign = _swig_property(_ivfgeo.ivfgeo_elem_t_binsign_get, _ivfgeo.ivfgeo_elem_t_binsign_set)
    def __init__(self): 
        this = _ivfgeo.new_ivfgeo_elem_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ivfgeo.delete_ivfgeo_elem_t
    __del__ = lambda self : None;
ivfgeo_elem_t_swigregister = _ivfgeo.ivfgeo_elem_t_swigregister
ivfgeo_elem_t_swigregister(ivfgeo_elem_t)
cvar = _ivfgeo.cvar
ivfgeo_nb_scales = cvar.ivfgeo_nb_scales
ivfgeo_nb_angles = cvar.ivfgeo_nb_angles

BURSTNORM_CANCEL_MM = _ivfgeo.BURSTNORM_CANCEL_MM
BURSTNORM_INTRA = _ivfgeo.BURSTNORM_INTRA
BURSTNORM_INTER = _ivfgeo.BURSTNORM_INTER
BURSTNORM_INTRA_FUNC_MASK = _ivfgeo.BURSTNORM_INTRA_FUNC_MASK
BURSTNORM_INTER_FUNC_MASK = _ivfgeo.BURSTNORM_INTER_FUNC_MASK
class ivfgeo_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ivfgeo_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ivfgeo_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nbvw"] = _ivfgeo.ivfgeo_t_nbvw_set
    __swig_getmethods__["nbvw"] = _ivfgeo.ivfgeo_t_nbvw_get
    if _newclass:nbvw = _swig_property(_ivfgeo.ivfgeo_t_nbvw_get, _ivfgeo.ivfgeo_t_nbvw_set)
    __swig_setmethods__["nbvec"] = _ivfgeo.ivfgeo_t_nbvec_set
    __swig_getmethods__["nbvec"] = _ivfgeo.ivfgeo_t_nbvec_get
    if _newclass:nbvec = _swig_property(_ivfgeo.ivfgeo_t_nbvec_get, _ivfgeo.ivfgeo_t_nbvec_set)
    __swig_setmethods__["nbvec_max"] = _ivfgeo.ivfgeo_t_nbvec_max_set
    __swig_getmethods__["nbvec_max"] = _ivfgeo.ivfgeo_t_nbvec_max_get
    if _newclass:nbvec_max = _swig_property(_ivfgeo.ivfgeo_t_nbvec_max_get, _ivfgeo.ivfgeo_t_nbvec_max_set)
    __swig_setmethods__["norm_type"] = _ivfgeo.ivfgeo_t_norm_type_set
    __swig_getmethods__["norm_type"] = _ivfgeo.ivfgeo_t_norm_type_get
    if _newclass:norm_type = _swig_property(_ivfgeo.ivfgeo_t_norm_type_get, _ivfgeo.ivfgeo_t_norm_type_set)
    __swig_setmethods__["elems"] = _ivfgeo.ivfgeo_t_elems_set
    __swig_getmethods__["elems"] = _ivfgeo.ivfgeo_t_elems_get
    if _newclass:elems = _swig_property(_ivfgeo.ivfgeo_t_elems_get, _ivfgeo.ivfgeo_t_elems_set)
    __swig_setmethods__["segsize"] = _ivfgeo.ivfgeo_t_segsize_set
    __swig_getmethods__["segsize"] = _ivfgeo.ivfgeo_t_segsize_get
    if _newclass:segsize = _swig_property(_ivfgeo.ivfgeo_t_segsize_get, _ivfgeo.ivfgeo_t_segsize_set)
    __swig_setmethods__["nbelems"] = _ivfgeo.ivfgeo_t_nbelems_set
    __swig_getmethods__["nbelems"] = _ivfgeo.ivfgeo_t_nbelems_get
    if _newclass:nbelems = _swig_property(_ivfgeo.ivfgeo_t_nbelems_get, _ivfgeo.ivfgeo_t_nbelems_set)
    __swig_setmethods__["norms"] = _ivfgeo.ivfgeo_t_norms_set
    __swig_getmethods__["norms"] = _ivfgeo.ivfgeo_t_norms_get
    if _newclass:norms = _swig_property(_ivfgeo.ivfgeo_t_norms_get, _ivfgeo.ivfgeo_t_norms_set)
    __swig_setmethods__["labels"] = _ivfgeo.ivfgeo_t_labels_set
    __swig_getmethods__["labels"] = _ivfgeo.ivfgeo_t_labels_get
    if _newclass:labels = _swig_property(_ivfgeo.ivfgeo_t_labels_get, _ivfgeo.ivfgeo_t_labels_set)
    __swig_setmethods__["tfidf"] = _ivfgeo.ivfgeo_t_tfidf_set
    __swig_getmethods__["tfidf"] = _ivfgeo.ivfgeo_t_tfidf_get
    if _newclass:tfidf = _swig_property(_ivfgeo.ivfgeo_t_tfidf_get, _ivfgeo.ivfgeo_t_tfidf_set)
    __swig_setmethods__["tfidf_weights"] = _ivfgeo.ivfgeo_t_tfidf_weights_set
    __swig_getmethods__["tfidf_weights"] = _ivfgeo.ivfgeo_t_tfidf_weights_get
    if _newclass:tfidf_weights = _swig_property(_ivfgeo.ivfgeo_t_tfidf_weights_get, _ivfgeo.ivfgeo_t_tfidf_weights_set)
    __swig_setmethods__["he_dist_w"] = _ivfgeo.ivfgeo_t_he_dist_w_set
    __swig_getmethods__["he_dist_w"] = _ivfgeo.ivfgeo_t_he_dist_w_get
    if _newclass:he_dist_w = _swig_property(_ivfgeo.ivfgeo_t_he_dist_w_get, _ivfgeo.ivfgeo_t_he_dist_w_set)
    __swig_setmethods__["he_thres"] = _ivfgeo.ivfgeo_t_he_thres_set
    __swig_getmethods__["he_thres"] = _ivfgeo.ivfgeo_t_he_thres_get
    if _newclass:he_thres = _swig_property(_ivfgeo.ivfgeo_t_he_thres_get, _ivfgeo.ivfgeo_t_he_thres_set)
    __swig_setmethods__["he_dis_weights"] = _ivfgeo.ivfgeo_t_he_dis_weights_set
    __swig_getmethods__["he_dis_weights"] = _ivfgeo.ivfgeo_t_he_dis_weights_get
    if _newclass:he_dis_weights = _swig_property(_ivfgeo.ivfgeo_t_he_dis_weights_get, _ivfgeo.ivfgeo_t_he_dis_weights_set)
    __swig_setmethods__["wgc_type"] = _ivfgeo.ivfgeo_t_wgc_type_set
    __swig_getmethods__["wgc_type"] = _ivfgeo.ivfgeo_t_wgc_type_get
    if _newclass:wgc_type = _swig_property(_ivfgeo.ivfgeo_t_wgc_type_get, _ivfgeo.ivfgeo_t_wgc_type_set)
    __swig_setmethods__["wgc_weights"] = _ivfgeo.ivfgeo_t_wgc_weights_set
    __swig_getmethods__["wgc_weights"] = _ivfgeo.ivfgeo_t_wgc_weights_get
    if _newclass:wgc_weights = _swig_property(_ivfgeo.ivfgeo_t_wgc_weights_get, _ivfgeo.ivfgeo_t_wgc_weights_set)
    __swig_setmethods__["scale_w"] = _ivfgeo.ivfgeo_t_scale_w_set
    __swig_getmethods__["scale_w"] = _ivfgeo.ivfgeo_t_scale_w_get
    if _newclass:scale_w = _swig_property(_ivfgeo.ivfgeo_t_scale_w_get, _ivfgeo.ivfgeo_t_scale_w_set)
    __swig_setmethods__["scale_weights"] = _ivfgeo.ivfgeo_t_scale_weights_set
    __swig_getmethods__["scale_weights"] = _ivfgeo.ivfgeo_t_scale_weights_get
    if _newclass:scale_weights = _swig_property(_ivfgeo.ivfgeo_t_scale_weights_get, _ivfgeo.ivfgeo_t_scale_weights_set)
    __swig_setmethods__["burstiness"] = _ivfgeo.ivfgeo_t_burstiness_set
    __swig_getmethods__["burstiness"] = _ivfgeo.ivfgeo_t_burstiness_get
    if _newclass:burstiness = _swig_property(_ivfgeo.ivfgeo_t_burstiness_get, _ivfgeo.ivfgeo_t_burstiness_set)
    __swig_setmethods__["mm_fd"] = _ivfgeo.ivfgeo_t_mm_fd_set
    __swig_getmethods__["mm_fd"] = _ivfgeo.ivfgeo_t_mm_fd_get
    if _newclass:mm_fd = _swig_property(_ivfgeo.ivfgeo_t_mm_fd_get, _ivfgeo.ivfgeo_t_mm_fd_set)
    __swig_setmethods__["mm_length"] = _ivfgeo.ivfgeo_t_mm_length_set
    __swig_getmethods__["mm_length"] = _ivfgeo.ivfgeo_t_mm_length_get
    if _newclass:mm_length = _swig_property(_ivfgeo.ivfgeo_t_mm_length_get, _ivfgeo.ivfgeo_t_mm_length_set)
    __swig_setmethods__["mm_base"] = _ivfgeo.ivfgeo_t_mm_base_set
    __swig_getmethods__["mm_base"] = _ivfgeo.ivfgeo_t_mm_base_get
    if _newclass:mm_base = _swig_property(_ivfgeo.ivfgeo_t_mm_base_get, _ivfgeo.ivfgeo_t_mm_base_set)
    def __init__(self): 
        this = _ivfgeo.new_ivfgeo_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ivfgeo.delete_ivfgeo_t
    __del__ = lambda self : None;
ivfgeo_t_swigregister = _ivfgeo.ivfgeo_t_swigregister
ivfgeo_t_swigregister(ivfgeo_t)

NB_BITS_VAL_DQID = _ivfgeo.NB_BITS_VAL_DQID
class ivfgeo_match_elem_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ivfgeo_match_elem_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ivfgeo_match_elem_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["score"] = _ivfgeo.ivfgeo_match_elem_t_score_set
    __swig_getmethods__["score"] = _ivfgeo.ivfgeo_match_elem_t_score_get
    if _newclass:score = _swig_property(_ivfgeo.ivfgeo_match_elem_t_score_get, _ivfgeo.ivfgeo_match_elem_t_score_set)
    __swig_setmethods__["ds"] = _ivfgeo.ivfgeo_match_elem_t_ds_set
    __swig_getmethods__["ds"] = _ivfgeo.ivfgeo_match_elem_t_ds_get
    if _newclass:ds = _swig_property(_ivfgeo.ivfgeo_match_elem_t_ds_get, _ivfgeo.ivfgeo_match_elem_t_ds_set)
    __swig_setmethods__["da"] = _ivfgeo.ivfgeo_match_elem_t_da_set
    __swig_getmethods__["da"] = _ivfgeo.ivfgeo_match_elem_t_da_get
    if _newclass:da = _swig_property(_ivfgeo.ivfgeo_match_elem_t_da_get, _ivfgeo.ivfgeo_match_elem_t_da_set)
    __swig_setmethods__["id"] = _ivfgeo.ivfgeo_match_elem_t_id_set
    __swig_getmethods__["id"] = _ivfgeo.ivfgeo_match_elem_t_id_get
    if _newclass:id = _swig_property(_ivfgeo.ivfgeo_match_elem_t_id_get, _ivfgeo.ivfgeo_match_elem_t_id_set)
    __swig_setmethods__["dqid"] = _ivfgeo.ivfgeo_match_elem_t_dqid_set
    __swig_getmethods__["dqid"] = _ivfgeo.ivfgeo_match_elem_t_dqid_get
    if _newclass:dqid = _swig_property(_ivfgeo.ivfgeo_match_elem_t_dqid_get, _ivfgeo.ivfgeo_match_elem_t_dqid_set)
    def __init__(self): 
        this = _ivfgeo.new_ivfgeo_match_elem_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ivfgeo.delete_ivfgeo_match_elem_t
    __del__ = lambda self : None;
ivfgeo_match_elem_t_swigregister = _ivfgeo.ivfgeo_match_elem_t_swigregister
ivfgeo_match_elem_t_swigregister(ivfgeo_match_elem_t)

class ivfgeo_match_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ivfgeo_match_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ivfgeo_match_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n"] = _ivfgeo.ivfgeo_match_t_n_set
    __swig_getmethods__["n"] = _ivfgeo.ivfgeo_match_t_n_get
    if _newclass:n = _swig_property(_ivfgeo.ivfgeo_match_t_n_get, _ivfgeo.ivfgeo_match_t_n_set)
    __swig_setmethods__["nmax"] = _ivfgeo.ivfgeo_match_t_nmax_set
    __swig_getmethods__["nmax"] = _ivfgeo.ivfgeo_match_t_nmax_get
    if _newclass:nmax = _swig_property(_ivfgeo.ivfgeo_match_t_nmax_get, _ivfgeo.ivfgeo_match_t_nmax_set)
    __swig_setmethods__["matches"] = _ivfgeo.ivfgeo_match_t_matches_set
    __swig_getmethods__["matches"] = _ivfgeo.ivfgeo_match_t_matches_get
    if _newclass:matches = _swig_property(_ivfgeo.ivfgeo_match_t_matches_get, _ivfgeo.ivfgeo_match_t_matches_set)
    def __init__(self): 
        this = _ivfgeo.new_ivfgeo_match_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ivfgeo.delete_ivfgeo_match_t
    __del__ = lambda self : None;
ivfgeo_match_t_swigregister = _ivfgeo.ivfgeo_match_t_swigregister
ivfgeo_match_t_swigregister(ivfgeo_match_t)


def ivfgeo_new(*args):
  return _ivfgeo.ivfgeo_new(*args)
ivfgeo_new = _ivfgeo.ivfgeo_new

def ivfgeo_delete(*args):
  return _ivfgeo.ivfgeo_delete(*args)
ivfgeo_delete = _ivfgeo.ivfgeo_delete

def ivfgeo_add(*args):
  return _ivfgeo.ivfgeo_add(*args)
ivfgeo_add = _ivfgeo.ivfgeo_add

def ivfgeo_check(*args):
  return _ivfgeo.ivfgeo_check(*args)
ivfgeo_check = _ivfgeo.ivfgeo_check

def ivfgeo_max_label(*args):
  return _ivfgeo.ivfgeo_max_label(*args)
ivfgeo_max_label = _ivfgeo.ivfgeo_max_label

def ivfgeo_query(*args):
  return _ivfgeo.ivfgeo_query(*args)
ivfgeo_query = _ivfgeo.ivfgeo_query

def ivfgeo_query_peek(*args):
  return _ivfgeo.ivfgeo_query_peek(*args)
ivfgeo_query_peek = _ivfgeo.ivfgeo_query_peek

def ivfgeo_read(*args):
  return _ivfgeo.ivfgeo_read(*args)
ivfgeo_read = _ivfgeo.ivfgeo_read

def ivfgeo_merge(*args):
  return _ivfgeo.ivfgeo_merge(*args)
ivfgeo_merge = _ivfgeo.ivfgeo_merge

def ivfgeo_crop(*args):
  return _ivfgeo.ivfgeo_crop(*args)
ivfgeo_crop = _ivfgeo.ivfgeo_crop

def ivfgeo_filter_duplicate_vw(*args):
  return _ivfgeo.ivfgeo_filter_duplicate_vw(*args)
ivfgeo_filter_duplicate_vw = _ivfgeo.ivfgeo_filter_duplicate_vw

def ivfgeo_mask_binsigns(*args):
  return _ivfgeo.ivfgeo_mask_binsigns(*args)
ivfgeo_mask_binsigns = _ivfgeo.ivfgeo_mask_binsigns

def ivfgeo_write(*args):
  return _ivfgeo.ivfgeo_write(*args)
ivfgeo_write = _ivfgeo.ivfgeo_write

def ivfgeo_set_wgc_type(*args):
  return _ivfgeo.ivfgeo_set_wgc_type(*args)
ivfgeo_set_wgc_type = _ivfgeo.ivfgeo_set_wgc_type

def ivfgeo_compute_norms(*args):
  return _ivfgeo.ivfgeo_compute_norms(*args)
ivfgeo_compute_norms = _ivfgeo.ivfgeo_compute_norms

def ivfgeo_compute_tfidf(*args):
  return _ivfgeo.ivfgeo_compute_tfidf(*args)
ivfgeo_compute_tfidf = _ivfgeo.ivfgeo_compute_tfidf

def ivfgeo_compute_scale_weights(*args):
  return _ivfgeo.ivfgeo_compute_scale_weights(*args)
ivfgeo_compute_scale_weights = _ivfgeo.ivfgeo_compute_scale_weights

def ivfgeo_compute_he_weights(*args):
  return _ivfgeo.ivfgeo_compute_he_weights(*args)
ivfgeo_compute_he_weights = _ivfgeo.ivfgeo_compute_he_weights

def ivfgeo_display(*args):
  return _ivfgeo.ivfgeo_display(*args)
ivfgeo_display = _ivfgeo.ivfgeo_display

def ivfgeo_summary(*args):
  return _ivfgeo.ivfgeo_summary(*args)
ivfgeo_summary = _ivfgeo.ivfgeo_summary

def ivfgeo_match_new(*args):
  return _ivfgeo.ivfgeo_match_new(*args)
ivfgeo_match_new = _ivfgeo.ivfgeo_match_new

def ivfgeo_match_delete(*args):
  return _ivfgeo.ivfgeo_match_delete(*args)
ivfgeo_match_delete = _ivfgeo.ivfgeo_match_delete

def ivfgeo_match_display(*args):
  return _ivfgeo.ivfgeo_match_display(*args)
ivfgeo_match_display = _ivfgeo.ivfgeo_match_display

def ivfgeo_count_nbelems(*args):
  return _ivfgeo.ivfgeo_count_nbelems(*args)
ivfgeo_count_nbelems = _ivfgeo.ivfgeo_count_nbelems

def ivfgeo_unbalanced_factor(*args):
  return _ivfgeo.ivfgeo_unbalanced_factor(*args)
ivfgeo_unbalanced_factor = _ivfgeo.ivfgeo_unbalanced_factor

def ivfgeo_compute_burstiness_hist(*args):
  return _ivfgeo.ivfgeo_compute_burstiness_hist(*args)
ivfgeo_compute_burstiness_hist = _ivfgeo.ivfgeo_compute_burstiness_hist

def ivfgeo_histo_diff_im_id(*args):
  return _ivfgeo.ivfgeo_histo_diff_im_id(*args)
ivfgeo_histo_diff_im_id = _ivfgeo.ivfgeo_histo_diff_im_id

def binsign_hamming(*args):
  return _ivfgeo.binsign_hamming(*args)
binsign_hamming = _ivfgeo.binsign_hamming

def binsign_cross_distances(*args):
  return _ivfgeo.binsign_cross_distances(*args)
binsign_cross_distances = _ivfgeo.binsign_cross_distances

def quantize_scale(*args):
  return _ivfgeo.quantize_scale(*args)
quantize_scale = _ivfgeo.quantize_scale

def quantize_angle(*args):
  return _ivfgeo.quantize_angle(*args)
quantize_angle = _ivfgeo.quantize_angle

def ivfgeo_compute_scale_weights_tab(*args):
  return _ivfgeo.ivfgeo_compute_scale_weights_tab(*args)
ivfgeo_compute_scale_weights_tab = _ivfgeo.ivfgeo_compute_scale_weights_tab

def ivfgeo_compute_wgc_tab(*args):
  return _ivfgeo.ivfgeo_compute_wgc_tab(*args)
ivfgeo_compute_wgc_tab = _ivfgeo.ivfgeo_compute_wgc_tab

def synth_wgc_tab(*args):
  return _ivfgeo.synth_wgc_tab(*args)
synth_wgc_tab = _ivfgeo.synth_wgc_tab
class query_stats_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, query_stats_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, query_stats_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n_images"] = _ivfgeo.query_stats_t_n_images_set
    __swig_getmethods__["n_images"] = _ivfgeo.query_stats_t_n_images_get
    if _newclass:n_images = _swig_property(_ivfgeo.query_stats_t_n_images_get, _ivfgeo.query_stats_t_n_images_set)
    __swig_setmethods__["n_points"] = _ivfgeo.query_stats_t_n_points_set
    __swig_getmethods__["n_points"] = _ivfgeo.query_stats_t_n_points_get
    if _newclass:n_points = _swig_property(_ivfgeo.query_stats_t_n_points_get, _ivfgeo.query_stats_t_n_points_set)
    __swig_setmethods__["n_visited_elements"] = _ivfgeo.query_stats_t_n_visited_elements_set
    __swig_getmethods__["n_visited_elements"] = _ivfgeo.query_stats_t_n_visited_elements_get
    if _newclass:n_visited_elements = _swig_property(_ivfgeo.query_stats_t_n_visited_elements_get, _ivfgeo.query_stats_t_n_visited_elements_set)
    __swig_setmethods__["n_he_success"] = _ivfgeo.query_stats_t_n_he_success_set
    __swig_getmethods__["n_he_success"] = _ivfgeo.query_stats_t_n_he_success_get
    if _newclass:n_he_success = _swig_property(_ivfgeo.query_stats_t_n_he_success_get, _ivfgeo.query_stats_t_n_he_success_set)
    __swig_setmethods__["n_mm_cancel"] = _ivfgeo.query_stats_t_n_mm_cancel_set
    __swig_getmethods__["n_mm_cancel"] = _ivfgeo.query_stats_t_n_mm_cancel_get
    if _newclass:n_mm_cancel = _swig_property(_ivfgeo.query_stats_t_n_mm_cancel_get, _ivfgeo.query_stats_t_n_mm_cancel_set)
    __swig_setmethods__["as_hist"] = _ivfgeo.query_stats_t_as_hist_set
    __swig_getmethods__["as_hist"] = _ivfgeo.query_stats_t_as_hist_get
    if _newclass:as_hist = _swig_property(_ivfgeo.query_stats_t_as_hist_get, _ivfgeo.query_stats_t_as_hist_set)
    __swig_setmethods__["elem_size"] = _ivfgeo.query_stats_t_elem_size_set
    __swig_getmethods__["elem_size"] = _ivfgeo.query_stats_t_elem_size_get
    if _newclass:elem_size = _swig_property(_ivfgeo.query_stats_t_elem_size_get, _ivfgeo.query_stats_t_elem_size_set)
    __swig_setmethods__["match_elem_size"] = _ivfgeo.query_stats_t_match_elem_size_set
    __swig_getmethods__["match_elem_size"] = _ivfgeo.query_stats_t_match_elem_size_get
    if _newclass:match_elem_size = _swig_property(_ivfgeo.query_stats_t_match_elem_size_get, _ivfgeo.query_stats_t_match_elem_size_set)
    def __init__(self): 
        this = _ivfgeo.new_query_stats_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ivfgeo.delete_query_stats_t
    __del__ = lambda self : None;
query_stats_t_swigregister = _ivfgeo.query_stats_t_swigregister
query_stats_t_swigregister(query_stats_t)

class ivfgeo_pq_point_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ivfgeo_pq_point_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ivfgeo_pq_point_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["scale"] = _ivfgeo.ivfgeo_pq_point_t_scale_set
    __swig_getmethods__["scale"] = _ivfgeo.ivfgeo_pq_point_t_scale_get
    if _newclass:scale = _swig_property(_ivfgeo.ivfgeo_pq_point_t_scale_get, _ivfgeo.ivfgeo_pq_point_t_scale_set)
    __swig_setmethods__["angle"] = _ivfgeo.ivfgeo_pq_point_t_angle_set
    __swig_getmethods__["angle"] = _ivfgeo.ivfgeo_pq_point_t_angle_get
    if _newclass:angle = _swig_property(_ivfgeo.ivfgeo_pq_point_t_angle_get, _ivfgeo.ivfgeo_pq_point_t_angle_set)
    def __init__(self): 
        this = _ivfgeo.new_ivfgeo_pq_point_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ivfgeo.delete_ivfgeo_pq_point_t
    __del__ = lambda self : None;
ivfgeo_pq_point_t_swigregister = _ivfgeo.ivfgeo_pq_point_t_swigregister
ivfgeo_pq_point_t_swigregister(ivfgeo_pq_point_t)

class ivfgeo_pq_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ivfgeo_pq_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ivfgeo_pq_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ivfpq"] = _ivfgeo.ivfgeo_pq_t_ivfpq_set
    __swig_getmethods__["ivfpq"] = _ivfgeo.ivfgeo_pq_t_ivfpq_get
    if _newclass:ivfpq = _swig_property(_ivfgeo.ivfgeo_pq_t_ivfpq_get, _ivfgeo.ivfgeo_pq_t_ivfpq_set)
    __swig_setmethods__["nim"] = _ivfgeo.ivfgeo_pq_t_nim_set
    __swig_getmethods__["nim"] = _ivfgeo.ivfgeo_pq_t_nim_get
    if _newclass:nim = _swig_property(_ivfgeo.ivfgeo_pq_t_nim_get, _ivfgeo.ivfgeo_pq_t_nim_set)
    __swig_setmethods__["norm_type"] = _ivfgeo.ivfgeo_pq_t_norm_type_set
    __swig_getmethods__["norm_type"] = _ivfgeo.ivfgeo_pq_t_norm_type_get
    if _newclass:norm_type = _swig_property(_ivfgeo.ivfgeo_pq_t_norm_type_get, _ivfgeo.ivfgeo_pq_t_norm_type_set)
    __swig_setmethods__["na_img"] = _ivfgeo.ivfgeo_pq_t_na_img_set
    __swig_getmethods__["na_img"] = _ivfgeo.ivfgeo_pq_t_na_img_get
    if _newclass:na_img = _swig_property(_ivfgeo.ivfgeo_pq_t_na_img_get, _ivfgeo.ivfgeo_pq_t_na_img_set)
    __swig_setmethods__["norms"] = _ivfgeo.ivfgeo_pq_t_norms_set
    __swig_getmethods__["norms"] = _ivfgeo.ivfgeo_pq_t_norms_get
    if _newclass:norms = _swig_property(_ivfgeo.ivfgeo_pq_t_norms_get, _ivfgeo.ivfgeo_pq_t_norms_set)
    __swig_setmethods__["im_ends"] = _ivfgeo.ivfgeo_pq_t_im_ends_set
    __swig_getmethods__["im_ends"] = _ivfgeo.ivfgeo_pq_t_im_ends_get
    if _newclass:im_ends = _swig_property(_ivfgeo.ivfgeo_pq_t_im_ends_get, _ivfgeo.ivfgeo_pq_t_im_ends_set)
    __swig_setmethods__["tot_pts"] = _ivfgeo.ivfgeo_pq_t_tot_pts_set
    __swig_getmethods__["tot_pts"] = _ivfgeo.ivfgeo_pq_t_tot_pts_get
    if _newclass:tot_pts = _swig_property(_ivfgeo.ivfgeo_pq_t_tot_pts_get, _ivfgeo.ivfgeo_pq_t_tot_pts_set)
    __swig_setmethods__["points"] = _ivfgeo.ivfgeo_pq_t_points_set
    __swig_getmethods__["points"] = _ivfgeo.ivfgeo_pq_t_points_get
    if _newclass:points = _swig_property(_ivfgeo.ivfgeo_pq_t_points_get, _ivfgeo.ivfgeo_pq_t_points_set)
    __swig_setmethods__["na_pts"] = _ivfgeo.ivfgeo_pq_t_na_pts_set
    __swig_getmethods__["na_pts"] = _ivfgeo.ivfgeo_pq_t_na_pts_get
    if _newclass:na_pts = _swig_property(_ivfgeo.ivfgeo_pq_t_na_pts_get, _ivfgeo.ivfgeo_pq_t_na_pts_set)
    __swig_setmethods__["tfidf"] = _ivfgeo.ivfgeo_pq_t_tfidf_set
    __swig_getmethods__["tfidf"] = _ivfgeo.ivfgeo_pq_t_tfidf_get
    if _newclass:tfidf = _swig_property(_ivfgeo.ivfgeo_pq_t_tfidf_get, _ivfgeo.ivfgeo_pq_t_tfidf_set)
    __swig_setmethods__["tfidf_weights"] = _ivfgeo.ivfgeo_pq_t_tfidf_weights_set
    __swig_getmethods__["tfidf_weights"] = _ivfgeo.ivfgeo_pq_t_tfidf_weights_get
    if _newclass:tfidf_weights = _swig_property(_ivfgeo.ivfgeo_pq_t_tfidf_weights_get, _ivfgeo.ivfgeo_pq_t_tfidf_weights_set)
    __swig_setmethods__["ma"] = _ivfgeo.ivfgeo_pq_t_ma_set
    __swig_getmethods__["ma"] = _ivfgeo.ivfgeo_pq_t_ma_get
    if _newclass:ma = _swig_property(_ivfgeo.ivfgeo_pq_t_ma_get, _ivfgeo.ivfgeo_pq_t_ma_set)
    __swig_setmethods__["ma_disratio"] = _ivfgeo.ivfgeo_pq_t_ma_disratio_set
    __swig_getmethods__["ma_disratio"] = _ivfgeo.ivfgeo_pq_t_ma_disratio_get
    if _newclass:ma_disratio = _swig_property(_ivfgeo.ivfgeo_pq_t_ma_disratio_get, _ivfgeo.ivfgeo_pq_t_ma_disratio_set)
    __swig_setmethods__["k"] = _ivfgeo.ivfgeo_pq_t_k_set
    __swig_getmethods__["k"] = _ivfgeo.ivfgeo_pq_t_k_get
    if _newclass:k = _swig_property(_ivfgeo.ivfgeo_pq_t_k_get, _ivfgeo.ivfgeo_pq_t_k_set)
    __swig_setmethods__["nthread"] = _ivfgeo.ivfgeo_pq_t_nthread_set
    __swig_getmethods__["nthread"] = _ivfgeo.ivfgeo_pq_t_nthread_get
    if _newclass:nthread = _swig_property(_ivfgeo.ivfgeo_pq_t_nthread_get, _ivfgeo.ivfgeo_pq_t_nthread_set)
    __swig_setmethods__["dist_w_type"] = _ivfgeo.ivfgeo_pq_t_dist_w_type_set
    __swig_getmethods__["dist_w_type"] = _ivfgeo.ivfgeo_pq_t_dist_w_type_get
    if _newclass:dist_w_type = _swig_property(_ivfgeo.ivfgeo_pq_t_dist_w_type_get, _ivfgeo.ivfgeo_pq_t_dist_w_type_set)
    __swig_setmethods__["sigma"] = _ivfgeo.ivfgeo_pq_t_sigma_set
    __swig_getmethods__["sigma"] = _ivfgeo.ivfgeo_pq_t_sigma_get
    if _newclass:sigma = _swig_property(_ivfgeo.ivfgeo_pq_t_sigma_get, _ivfgeo.ivfgeo_pq_t_sigma_set)
    __swig_setmethods__["wgc_type"] = _ivfgeo.ivfgeo_pq_t_wgc_type_set
    __swig_getmethods__["wgc_type"] = _ivfgeo.ivfgeo_pq_t_wgc_type_get
    if _newclass:wgc_type = _swig_property(_ivfgeo.ivfgeo_pq_t_wgc_type_get, _ivfgeo.ivfgeo_pq_t_wgc_type_set)
    __swig_setmethods__["wgc_weights"] = _ivfgeo.ivfgeo_pq_t_wgc_weights_set
    __swig_getmethods__["wgc_weights"] = _ivfgeo.ivfgeo_pq_t_wgc_weights_get
    if _newclass:wgc_weights = _swig_property(_ivfgeo.ivfgeo_pq_t_wgc_weights_get, _ivfgeo.ivfgeo_pq_t_wgc_weights_set)
    __swig_setmethods__["burstiness"] = _ivfgeo.ivfgeo_pq_t_burstiness_set
    __swig_getmethods__["burstiness"] = _ivfgeo.ivfgeo_pq_t_burstiness_get
    if _newclass:burstiness = _swig_property(_ivfgeo.ivfgeo_pq_t_burstiness_get, _ivfgeo.ivfgeo_pq_t_burstiness_set)
    __swig_setmethods__["scale_w"] = _ivfgeo.ivfgeo_pq_t_scale_w_set
    __swig_getmethods__["scale_w"] = _ivfgeo.ivfgeo_pq_t_scale_w_get
    if _newclass:scale_w = _swig_property(_ivfgeo.ivfgeo_pq_t_scale_w_get, _ivfgeo.ivfgeo_pq_t_scale_w_set)
    __swig_setmethods__["scale_weights"] = _ivfgeo.ivfgeo_pq_t_scale_weights_set
    __swig_getmethods__["scale_weights"] = _ivfgeo.ivfgeo_pq_t_scale_weights_get
    if _newclass:scale_weights = _swig_property(_ivfgeo.ivfgeo_pq_t_scale_weights_get, _ivfgeo.ivfgeo_pq_t_scale_weights_set)
    def __init__(self): 
        this = _ivfgeo.new_ivfgeo_pq_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ivfgeo.delete_ivfgeo_pq_t
    __del__ = lambda self : None;
ivfgeo_pq_t_swigregister = _ivfgeo.ivfgeo_pq_t_swigregister
ivfgeo_pq_t_swigregister(ivfgeo_pq_t)


def ivfgeo_pq_new(*args):
  return _ivfgeo.ivfgeo_pq_new(*args)
ivfgeo_pq_new = _ivfgeo.ivfgeo_pq_new

def ivfgeo_pq_dup(*args):
  return _ivfgeo.ivfgeo_pq_dup(*args)
ivfgeo_pq_dup = _ivfgeo.ivfgeo_pq_dup

def ivfgeo_pq_merge(*args):
  return _ivfgeo.ivfgeo_pq_merge(*args)
ivfgeo_pq_merge = _ivfgeo.ivfgeo_pq_merge

def ivfgeo_pq_display(*args):
  return _ivfgeo.ivfgeo_pq_display(*args)
ivfgeo_pq_display = _ivfgeo.ivfgeo_pq_display

def ivfgeo_pq_add(*args):
  return _ivfgeo.ivfgeo_pq_add(*args)
ivfgeo_pq_add = _ivfgeo.ivfgeo_pq_add

def ivfgeo_pq_add_with_vw(*args):
  return _ivfgeo.ivfgeo_pq_add_with_vw(*args)
ivfgeo_pq_add_with_vw = _ivfgeo.ivfgeo_pq_add_with_vw

def ivfgeo_pq_query(*args):
  return _ivfgeo.ivfgeo_pq_query(*args)
ivfgeo_pq_query = _ivfgeo.ivfgeo_pq_query

def ivfgeo_pq_compute_tfidf(*args):
  return _ivfgeo.ivfgeo_pq_compute_tfidf(*args)
ivfgeo_pq_compute_tfidf = _ivfgeo.ivfgeo_pq_compute_tfidf

def ivfgeo_pq_compute_norms(*args):
  return _ivfgeo.ivfgeo_pq_compute_norms(*args)
ivfgeo_pq_compute_norms = _ivfgeo.ivfgeo_pq_compute_norms

def ivfgeo_pq_compute_scale_weights(*args):
  return _ivfgeo.ivfgeo_pq_compute_scale_weights(*args)
ivfgeo_pq_compute_scale_weights = _ivfgeo.ivfgeo_pq_compute_scale_weights

def ivfgeo_pq_set_wgc_type(*args):
  return _ivfgeo.ivfgeo_pq_set_wgc_type(*args)
ivfgeo_pq_set_wgc_type = _ivfgeo.ivfgeo_pq_set_wgc_type

def ivfgeo_pq_fwrite(*args):
  return _ivfgeo.ivfgeo_pq_fwrite(*args)
ivfgeo_pq_fwrite = _ivfgeo.ivfgeo_pq_fwrite

def ivfgeo_pq_fread(*args):
  return _ivfgeo.ivfgeo_pq_fread(*args)
ivfgeo_pq_fread = _ivfgeo.ivfgeo_pq_fread


